version: '3.8'

services:
    wsgiserver:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/Fit_Library
        entrypoint: ./docker/backend/web-entrypoint.sh

