# Generated by Django 5.0.3 on 2024-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[("Для начинающих", "Easy"), ("Средний", "Medium"), ("Продвинутый", "Hard")],
                max_length=50,
                verbose_name="Уровень сложности",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="type_exercise",
            field=models.CharField(
                choices=[
                    ("Кардио", "Cardio"),
                    ("Силовые", "Power"),
                    ("Растяжка", "Stretching"),
                    ("Аэробика", "Aerobics"),
                ],
                max_length=50,
                verbose_name="Тип упражнения",
            ),
        ),
    ]
